### ISSUE TITLE
Maps do not have data file

### ISSUE THREAD

**Issue by xyc9471** [worldbank/Stata-IE-Visual-Library#39]
The codes of 'Maps' have one line that does not work:

`merge 1:1 iso_a2 using data, keep(1 3) nogen`

Stata states there is no data.dta file. In the folder "Map displaying levels of a variable", there is no data.dta file.

**Comment by bbdaniels** [comment]
Hm, this isn't mine, sorry!

**Comment by bbdaniels** [comment]
I added a new map with working code and data however in https://github.com/worldbank/Stata-IE-Visual-Library/pull/45

**Comment by luizaandrade** [comment]
Oops, sorry. I think this must be Marcela's then. Thanks for the new map!

**Comment by xyc9471** [comment]
> The codes of 'Maps' have one line that does not work:
> 
> `merge 1:1 iso_a2 using data, keep(1 3) nogen`
> 
> Stata states there is no data.dta file. In the folder "Map displaying levels of a variable", there is no data.dta file.

Uploaded the data needed for map, now the code works.
