### ISSUE TITLE
Any reason why it would only work for logistic regression and not regular regression? 

### ISSUE THREAD

**Issue by escandethomas** [worldbank/Stata-IE-Visual-Library#51]
https://github.com/worldbank/Stata-IE-Visual-Library/blob/8401d5830aec0d9bfd28ebdf04caf12c720bded1/ado%20files/chartable.sthlp#L13-L14

In the ado file, case0 and case1 are required options, but there is no mention of them in the help file!

**Comment by bbdaniels** [comment]
Yeah, that's just how it's written. Couldn't figure out the scaling of the axes in time before publishing so didn't generalize. See #50 as well.
